#! /usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2015 Junko Tsuji

# Guess fastq quality encoding offset by checking the range
# of the ASCII-encoded quality scores in a fastq input.

import sys, os.path, fileinput, signal
from optparse import OptionParser

def fastqInput(lines):
    read = []
    for i, x in enumerate(lines):
        read.append(x.rstrip())
        if i % 4 == 3:
            yield read
            read = []

def qualOffset(opts, args):
    q_char = set()
    platform = [ ('Sanger/Illumina-1.8+', 33,  76, 33),
                 ('Illumina-1.5+',        67, 104, 64),
                 ('Illumina-1.3+',        54, 104, 64),
                 ('Solexa',               59, 104, 64) ]
    read_cnt = 1
    sample_num = 50000
    fastqs = fastqInput(fileinput.input(args[0]))
    for read in fastqs:
        q_char = q_char.union([q for q in read[-1]])
        read_cnt += 1
        if read_cnt == sample_num: break
    q_int = sorted([ord(ch) for ch in q_char])
    if len(q_int) == 1:
        raise Exception("unknown quality encoding")
    for pl in platform:
        # second first and last elements
        if pl[1] <= q_int[1] and q_int[-2] <= pl[2]:
            print "%s:base=%d" % (pl[0], pl[3])
            return
    raise Exception("unknown quality encoding")

if __name__ == "__main__":
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    usage = "%prog <fastq>"
    description = "Estimate quality score encoding."

    op = OptionParser(usage=usage, description=description)
    (opts, args) = op.parse_args()

    if len(args) != 1:
        op.error("input fastq")
    try:
        qualOffset(opts, args)
    except KeyboardInterrupt: pass
    except Exception, e:
        prog = os.path.basename(sys.argv[0])
        sys.exit(prog + ": error: " + str(e))
